name: Go

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest

    services: 
      mysql:
        image: mysql
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: casbin
        ports:
          - 3306:3306
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      dameng:
        image: laotie255/dameng_single:dm8_20241022_rev244896_x86_rh6_64
        env:
          SYSDBA_PWD: SYSDBA001
          PAGE_SIZE: 8
          EXTENT_SIZE: 16
          LOG_SIZE: 256
          BLANK_PAD_MODE: 0
          CASE_SENSITIVE: 0
          UNICODE_FLAG: 1
          LENGTH_IN_CHAR: 0
          BUFFER: 1000
          LANG: en_US.UTF-8
          MODE: dmsingle
          INSTANCE_NAME: dm8_test
        ports:
          - 5236:5236

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - uses: actions/checkout@v2
      - name: Run Unit tests
        run: go test -v -coverprofile=profile.cov ./...
      
      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=profile.cov -service=github

  semantic-release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Run semantic-release
        if: github.repository == 'casdoor/xorm-adapter' && github.event_name == 'push'
        run: |
          npm install --save-dev semantic-release@17.2.4
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}